/* -*- buffer-read-only: t -*-
   !!!!!!!   DO NOT EDIT THIS FILE   !!!!!!!
   This file is built by regen_perly.pl from perly.y.
   Any changes made here will be lost!
 */

#ifdef PERL_CORE
/* A Bison parser, made by GNU Bison 2.3.  */

/* Skeleton interface for Bison's Yacc-like parsers in C

   Copyright (C) 1984, 1989, 1990, 2000, 2001, 2002, 2003, 2004, 2005, 2006
   Free Software Foundation, Inc.

   This program is free software; you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation; either version 2, or (at your option)
   any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program; if not, write to the Free Software
   Foundation, Inc., 51 Franklin Street, Fifth Floor,
   Boston, MA 02110-1301, USA.  */

/* As a special exception, you may create a larger work that contains
   part or all of the Bison parser skeleton and distribute that work
   under terms of your choice, so long as that work isn't itself a
   parser generator using the skeleton or a modified version thereof
   as a parser skeleton.  Alternatively, if you modify or redistribute
   the parser skeleton itself, you may (at your option) remove this
   special exception, which will cause the skeleton and the resulting
   Bison output files to be licensed under the GNU General Public
   License without this special exception.

   This special exception was added by the Free Software Foundation in
   version 2.2 of Bison.  */

/* Tokens.  */
#ifndef YYTOKENTYPE
# define YYTOKENTYPE
   /* Put the tokens into the symbol table, so that GDB and other debuggers
      know about them.  */
   enum yytokentype {
     GRAMPROG = 258,
     GRAMEXPR = 259,
     GRAMBLOCK = 260,
     GRAMBARESTMT = 261,
     GRAMFULLSTMT = 262,
     GRAMSTMTSEQ = 263,
     WORD = 264,
     METHOD = 265,
     FUNCMETH = 266,
     THING = 267,
     PMFUNC = 268,
     PRIVATEREF = 269,
     QWLIST = 270,
     FUNC0OP = 271,
     FUNC0SUB = 272,
     UNIOPSUB = 273,
     LSTOPSUB = 274,
     INFIXSUB = 275,
     PLUGEXPR = 276,
     PLUGSTMT = 277,
     LABEL = 278,
     FORMAT = 279,
     SUB = 280,
     ANONSUB = 281,
     PACKAGE = 282,
     USE = 283,
     WHILE = 284,
     UNTIL = 285,
     IF = 286,
     UNLESS = 287,
     ELSE = 288,
     ELSIF = 289,
     CONTINUE = 290,
     FOR = 291,
     GIVEN = 292,
     WHEN = 293,
     DEFAULT = 294,
     LOOPEX = 295,
     DOTDOT = 296,
     YADAYADA = 297,
     FUNC0 = 298,
     FUNC1 = 299,
     FUNC = 300,
     UNIOP = 301,
     LSTOP = 302,
     RELOP = 303,
     EQOP = 304,
     MULOP = 305,
     ADDOP = 306,
     DOLSHARP = 307,
     DO = 308,
     HASHBRACK = 309,
     NOAMP = 310,
     LOCAL = 311,
     MY = 312,
     REQUIRE = 313,
     COLONATTR = 314,
     FORMLBRACK = 315,
     FORMRBRACK = 316,
     PREC_LOW = 317,
     DOROP = 318,
     OROP = 319,
     ANDOP = 320,
     NOTOP = 321,
     ASSIGNOP = 322,
     DORDOR = 323,
     OROR = 324,
     ANDAND = 325,
     BITOROP = 326,
     BITANDOP = 327,
     SHIFTOP = 328,
     MATCHOP = 329,
     REFGEN = 330,
     UMINUS = 331,
     POWOP = 332,
     POSTDEC = 333,
     POSTINC = 334,
     PREDEC = 335,
     PREINC = 336,
     ARROW = 337,
     PEG = 338
   };
#endif
/* Tokens.  */
#define GRAMPROG 258
#define GRAMEXPR 259
#define GRAMBLOCK 260
#define GRAMBARESTMT 261
#define GRAMFULLSTMT 262
#define GRAMSTMTSEQ 263
#define WORD 264
#define METHOD 265
#define FUNCMETH 266
#define THING 267
#define PMFUNC 268
#define PRIVATEREF 269
#define QWLIST 270
#define FUNC0OP 271
#define FUNC0SUB 272
#define UNIOPSUB 273
#define LSTOPSUB 274
#define INFIXSUB 275
#define PLUGEXPR 276
#define PLUGSTMT 277
#define LABEL 278
#define FORMAT 279
#define SUB 280
#define ANONSUB 281
#define PACKAGE 282
#define USE 283
#define WHILE 284
#define UNTIL 285
#define IF 286
#define UNLESS 287
#define ELSE 288
#define ELSIF 289
#define CONTINUE 290
#define FOR 291
#define GIVEN 292
#define WHEN 293
#define DEFAULT 294
#define LOOPEX 295
#define DOTDOT 296
#define YADAYADA 297
#define FUNC0 298
#define FUNC1 299
#define FUNC 300
#define UNIOP 301
#define LSTOP 302
#define RELOP 303
#define EQOP 304
#define MULOP 305
#define ADDOP 306
#define DOLSHARP 307
#define DO 308
#define HASHBRACK 309
#define NOAMP 310
#define LOCAL 311
#define MY 312
#define REQUIRE 313
#define COLONATTR 314
#define FORMLBRACK 315
#define FORMRBRACK 316
#define PREC_LOW 317
#define DOROP 318
#define OROP 319
#define ANDOP 320
#define NOTOP 321
#define ASSIGNOP 322
#define DORDOR 323
#define OROR 324
#define ANDAND 325
#define BITOROP 326
#define BITANDOP 327
#define SHIFTOP 328
#define MATCHOP 329
#define REFGEN 330
#define UMINUS 331
#define POWOP 332
#define POSTDEC 333
#define POSTINC 334
#define PREDEC 335
#define PREINC 336
#define ARROW 337
#define PEG 338




#ifdef PERL_IN_TOKE_C
static bool
S_is_opval_token(int type) {
    switch (type) {
    case FUNC0OP:
    case FUNC0SUB:
    case FUNCMETH:
    case INFIXSUB:
    case LSTOPSUB:
    case METHOD:
    case PLUGEXPR:
    case PLUGSTMT:
    case PMFUNC:
    case PRIVATEREF:
    case QWLIST:
    case THING:
    case UNIOPSUB:
    case WORD:
	return 1;
    }
    return 0;
}
#endif /* PERL_IN_TOKE_C */
#endif /* PERL_CORE */
#if ! defined YYSTYPE && ! defined YYSTYPE_IS_DECLARED
typedef union YYSTYPE
{
    I32	ival; /* __DEFAULT__ (marker for regen_perly.pl;
				must always be 1st union member) */
    char *pval;
    OP *opval;
    GV *gvval;
#ifdef PERL_IN_MADLY_C
    TOKEN* p_tkval;
    TOKEN* i_tkval;
#else
    char *p_tkval;
    I32	i_tkval;
#endif
#ifdef PERL_MAD
    TOKEN* tkval;
#endif
}
/* Line 1529 of yacc.c.  */
	YYSTYPE;
# define yystype YYSTYPE /* obsolescent; will be withdrawn */
# define YYSTYPE_IS_DECLARED 1
# define YYSTYPE_IS_TRIVIAL 1
#endif




/* Generated from:
 * e44ef641d4558f31b3a22bd9841e32763e41b50bca95741b4b7a2b9dd237ec9e perly.y
 * 73288b53f1f6dc0183252a5a8e4f39cfe36e357e77233704fad3021fee88eb5b regen_perly.pl
 * ex: set ro: */
